version: "3"
services:
  lab:
    build: .
    container_name: "lab"
    volumes:
      - ./lab:/lab
    ports:
      - "18888:18888"
    command:
      jupyter-lab --allow-root --no-browser --ip=0.0.0.0 --port=18888
